[package]
name = "raylib-examples"
version = "0.11.0"
authors = ["David Ayeke"]
edition = "2018"
license = "Zlib"
readme = "../README.md"
repository = "https://github.com/deltaphc/raylib-rs"


[dependencies]
raylib = { version = "0.11", path = "../raylib" }
structopt = "0.2"

[[bin]]
name = "logo"
path = "./logo.rs"

[[bin]]
name = "camera2D"
path = "./camera2D.rs"

[[bin]]
name = "raymarch"
path = "./raymarch.rs"

# [[bin]]
# name = "logoraw"
# path = "./logo_raw.rs"

# [[bin]]
# name = "triangleraw"
# path = "./triangle_raw.rs"

# [[bin]]
# name = "font"
# path = "./font.rs"

# [[bin]]
# name = "drop"
# path = "./drop.rs"