[package]
name = "raylib-examples"
version = "0.11.0"
authors = ["David Ayeke"]
edition = "2018"
license = "Zlib"
readme = "../README.md"
repository = "https://github.com/deltaphc/raylib-rs"


[dependencies]
raylib = { version = "0.11", path = "../raylib" }
structopt = "0.2"
specs-derive = "0.4"

[dependencies.specs]
version = "0.14"
default-features = false

[[bin]]
name = "specs"
path = "./specs.rs"

[[bin]]
name = "arkanoid"
path = "./arkanoid.rs"

[[bin]]
name = "logo"
path = "./logo.rs"

[[bin]]
name = "rgui"
path = "./rgui.rs"

[[bin]]
name = "file"
path = "./file.rs"

[[bin]]
name = "camera2D"
path = "./camera2D.rs"

[[bin]]
name = "raymarch"
path = "./raymarch.rs"

[[bin]]
name = "font"
path = "./font.rs"

[[bin]]
name = "drop"
path = "./drop.rs"