[package]
name = "raylib-test"
version = "1.1.0"
authors = ["David Ayeke"]
edition = "2018"
license = "Zlib"
readme = "../README.md"
repository = "https://github.com/deltaphc/raylib-rs"


[dependencies]
raylib = { version = "1.1", path = "../raylib" }
lazy_static = "1.4.0"
