name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build -p raylib --verbose
    # - name: Run tests [Requires window system]
      # run: cargo test -p raylib-test --verbose
